# Generated by Django 2.1.7 on 2019-02-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190226_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='english',
            new_name='Equipment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='tibetan',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='english',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tibetan',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='exercise',
            name='CardStrenFlex',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Difficulty',
            field=models.CharField(choices=[('Ez', 'Easy'), ('Md', 'Moderate'), ('Ha', 'Hard'), ('Br', 'Brutal')], default='Ez', max_length=2),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Muscles',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='NumPeople',
            field=models.CharField(choices=[('Self', 'Individual'), ('Pair', 'Pair'), ('Group', 'Group')], default='Self', max_length=4),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Reps',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Sets',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Time',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Calories',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='CookTime',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='DietaryRestr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='PrepTime',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='RecipeName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Servings',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Translation',
            field=models.TextField(default=''),
        ),
    ]
