# Generated by Django 2.1.7 on 2019-03-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190227_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='CardStrenFlex',
            new_name='Cardio_Strength_Flex',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='NumPeople',
            new_name='Number_of_People',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='DietaryRestr',
            new_name='DietaryRestriction',
        ),
    ]
